InnoMasketss/Controllers/AdminUsuarioController.cs
using InnoMasketss.Data;
using InnoMasketss.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data.SqlClient;
using System.Data;
using InnoMasketss.Data.Servicios;
using X.PagedList;

namespace InnoMasketss.Controllers
{
    public class AdminUsuarioController : Controller
    {
        private readonly Contexto _contexto;

        private readonly UsuarioServicio _usuarioServicio;

        public AdminUsuarioController(Contexto contexto)
        {
            _contexto = contexto;
            _usuarioServicio = new UsuarioServicio(contexto);
        }

        public IActionResult Index(string buscar, int? pagina)
        {
            try
            {
                var usuarios = _usuarioServicio.ListarUsuarios();
                if (!String.IsNullOrEmpty(buscar))

                    //Buscar mediante el correo o Nombre de usuario
                    usuarios=usuarios.Where(u=>u.Correo!=null && u.Correo.Contains(buscar) || u.NombreUsuario !=null && u.NombreUsuario.Contains(buscar)).ToList();
                usuarios= usuarios.OrderBy(u => u.NombreUsuario).ToList();

                List<SelectListItem> roles = _usuarioServicio.ListarRoles().Select(r => new SelectListItem
                {
                    //Se mostrara su rol ya sea administrador o usuario
                    Value = r.RolId.ToString(),
                    Text = r.Nombre
                }).ToList();
                ViewBag.Roles = roles;

                int pageSize = 10;
                int pageNumber = (pagina ?? 1);  //si no re asigna ningun numerode pagina se establecera a la pagina 1
                var usuariospaginados = usuarios.ToPagedList(pageNumber, pageSize);

                return View(usuariospaginados);  //Datos ya actualizados
            }
            catch (System.Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        public IActionResult Create()
        {
            try
            {
                //Lista desplegable de roles
                List<SelectListItem> roles = _usuarioServicio.ListarRoles().Select(r => new SelectListItem
                {
                    Value = r.RolId.ToString(),
                    Text = r.Nombre
                }).ToList();
                ViewBag.Roles = roles;
            }
            catch (System.Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            return View();
        }

        [HttpPost]
        public IActionResult Create(Usuario usuario)
        {
            try
            {
                using (SqlConnection con = new(_contexto.Conexion))
                {
                    using (SqlCommand cmd = new("RegistrarUsuario", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@Nombre", usuario.Nombre);
                        cmd.Parameters.AddWithValue("@Apellido", usuario.Apellido);
                        cmd.Parameters.AddWithValue("@Correo", usuario.Correo);
                        string hashedPassword = BCrypt.Net.BCrypt.HashPassword(usuario.Contrasena);
                        cmd.Parameters.AddWithValue("@Contrasena", hashedPassword);
                        cmd.Parameters.AddWithValue("@RolId", usuario.RolId);
                        cmd.Parameters.AddWithValue("@NombreUsuario", usuario.NombreUsuario);
                        cmd.Parameters.AddWithValue("@Estado", usuario.Estado);
                        cmd.Parameters.AddWithValue("@Token", usuario.Token);
                        cmd.Parameters.AddWithValue("@FechaExpiracion", usuario.FechaExpiracion);

                        con.Open();
                        cmd.ExecuteNonQuery();
                    }
                    return RedirectToAction("Index");
                }
            }
            catch (System.Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(usuario);
            }
        }

        public IActionResult Edit(int id)
        {
            try
            {
                var usuario = _usuarioServicio.ObtenerUsuarioId(id);
                if (usuario == null)
                    return NotFound();

                List<SelectListItem> roles = _usuarioServicio.ListarRoles().Select(r => new SelectListItem
                {
                    Value = r.RolId.ToString(),
                    Text = r.Nombre
                }).ToList();
                ViewBag.Roles = roles;

                return View(usuario);
            }
            catch (System.Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        [HttpPost]
        public IActionResult Edit(int id, Usuario usuario)
        {
            if (id != usuario.UsuariosId) //Si no coincide el id con ningun registro enviara mensaje de "No Enconttrado"
                return NotFound();
            try
            {
                using (SqlConnection con = new(_contexto.Conexion))
                {
                    using (SqlCommand cmd = new("ActualizarUsuarios", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@UsuariosId", usuario.UsuariosId);
                        cmd.Parameters.AddWithValue("@Nombre", usuario.Nombre);
                        cmd.Parameters.AddWithValue("@Apellido", usuario.Apellido);
                        cmd.Parameters.AddWithValue("@RolId", usuario.RolId);
                        cmd.Parameters.AddWithValue("@Estado", usuario.Estado);

                        con.Open();
                        cmd.ExecuteNonQuery();
                    }

                }
                return RedirectToAction("Index");

            }
            catch (System.Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(usuario);
            }
        }

        public IActionResult Delete(int id)
        {
            try
            {
                var usuario = _usuarioServicio.ObtenerUsuarioId(id);
                if (usuario == null)
                    return NotFound();

                return View(usuario);
            }
            catch (System.Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();

            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                using (SqlConnection con = new SqlConnection(_contexto.Conexion))
                {
                    using (SqlCommand cmd = new("EliminarUsuario", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@UsuariosId", id);
                        con.Open();
                        cmd.ExecuteNonQuery();
                    }
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception e)
            {
                ViewBag.Error = e.Message;
                return View(_usuarioServicio.ObtenerUsuarioId(id));
            }
        }
    }
}

InnoMasketss/Controllers/CuentaController.cs
using InnoMasketss.Data.Servicios;
using InnoMasketss.Data;
using InnoMasketss.Models.ViewModels;
using InnoMasketss.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient; 
using System.Data;
using System.Security.Claims;

namespace InnoMasketss.Controllers
{
    public class CuentaController : Controller
    {
        private readonly Contexto _contexto;

        private readonly UsuarioServicio _usuarioServicio;

        public CuentaController(Contexto con)
        {
            _contexto = con;
            _usuarioServicio = new UsuarioServicio(con);
        }

        public IActionResult Registrar()
        {
            return View();
        }

        //Medida de seguraridad que nos ayuda a prevenir ataques ccrs
        [HttpPost, ValidateAntiForgeryToken]

        //Controlador para registrar usuario
        public IActionResult Registrar(Usuario model)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    using (var connection = new SqlConnection(_contexto.Conexion))
                    {
                        connection.Open();
                        using (var command = new SqlCommand("RegistrarUsuario", connection))
                        {
                            command.CommandType = CommandType.StoredProcedure;
                            command.Parameters.AddWithValue("@Nombre", model.Nombre);
                            command.Parameters.AddWithValue("@Apellido", model.Apellido);
                            command.Parameters.AddWithValue("@Correo", model.Correo);
                            string hashedPasswork = BCrypt.Net.BCrypt.HashPassword(model.Contrasena);  //Encriptar Contraseña
                            command.Parameters.AddWithValue("@Contrasena", hashedPasswork);
                            command.Parameters.AddWithValue("@NombreUsuario", model.NombreUsuario);
                            DateTime fechaexpiracion = DateTime.UtcNow.AddMinutes(10);
                            command.Parameters.AddWithValue("@FechaExpiracion", fechaexpiracion);
                            var token = Guid.NewGuid();
                            command.Parameters.AddWithValue("@Token", token);
                            command.ExecuteNonQuery();

                            Email email = new();
                            if (model.Correo != null)
                                email.Enviar(model.Correo, token.ToString());
                        }
                    }
                    return RedirectToAction("Token");
                }
                catch (SqlException ex)
                {

                    if (ex.Number == 2627)
                        ViewBag.Error = "El correo electorico y/o nombre de usuario ya existe!.";
                    else
                        ViewBag.Error = "Ocurrio al intentar ingresar al usuario.";
                    throw;
                }
            }
            return View();
        }

        public IActionResult Token()
        {
            string token = Request.Query["valor"];

            if (token != null)
            {
                try
                {
                    using (SqlConnection con = new SqlConnection(_contexto.Conexion))
                    {
                        using (SqlCommand cmd = new SqlCommand("ActivarCuenta", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@Token", token);
                            DateTime fechaExpiracion = DateTime.UtcNow.AddMinutes(5);
                            cmd.Parameters.AddWithValue("@Fecha", fechaExpiracion);
                            con.Open();
                            var resultado = cmd.ExecuteScalar();

                            int activada = Convert.ToInt32(resultado);

                            if (activada == 1)
                                ViewData["mensaje"] = "Su cuenta ha sido validada exitosamente";
                            else
                                ViewData["mensaje"] = "Su enlace de activacion ha expirado";

                            con.Close();

                        }
                    }
                }
                catch (System.Exception e)
                {

                    ViewData["mensaje"] = e.Message;
                    return View();
                }

            }
            else
            {
                ViewData["mensaje"] = "Verifique su correo para activar su cuenta";
                return View();
            }
            return View();
        }

        //Metodo para Autenticarse
        //Si ya esta autenticado
        public IActionResult Login()
        {
            try
            {
                ClaimsPrincipal c = HttpContext.User;
                if (c.Identity != null)
                {
                    if (c.Identity.IsAuthenticated)
                        return RedirectToAction("Index", "Home");
                }
            }
            catch (System.Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModels model)
        {
            if (!ModelState.IsValid)
                return View(model); //En caso que no sea valido retonara a la vista con  el modelo

            try
            {
                using (SqlConnection con = new(_contexto.Conexion))
                {
                    using (SqlCommand cmd = new("ValidarUsuario", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@Correo", model.Correo);
                        con.Open();
                        try
                        {
                            using (var dr = cmd.ExecuteReader())
                            {
                                if (dr.Read())
                                {
                                    bool passwordMatch = BCrypt.Net.BCrypt.Verify(model.Contrasena, dr["Contrasena"].ToString()); //
                                    if (passwordMatch)
                                    {
                                        DateTime fechaexpiracion = DateTime.UtcNow;

                                        //Reenvio de un nuevo Token y el tiempo de expiracion ya caduco
                                        if (!(bool)dr["Estado"] && dr["FechaExpiracion"].ToString() != fechaexpiracion.ToString())
                                        {
                                            if (model.Correo != null)
                                                _usuarioServicio.ActualizarToken(model.Correo);

                                            ViewBag.Error = "Su cuenta no ha sido activada, se ha reenviado un correo de activacio, verique su bandeja";


                                        }
                                        else if (!(bool)dr["Estado"])
                                            ViewBag.Error = "Su cuenta no ha sido activada, verifique su bandeja de entrada";

                                        //Si el procedimiento se hizo correctamente y la cuenta esta activa
                                        else
                                        {
                                            string? nombreusuario = dr["NombreUsuario"].ToString();
                                            int idUsuario = (int)dr["UsuariosId"];

                                            if (nombreusuario != null)
                                            {
                                                //Guardo de informacion para autenticacion mediante un Claim
                                                var claims = new List<Claim>()
                                                {
                                                    new Claim(ClaimTypes.NameIdentifier, nombreusuario),
                                                    new Claim("UsuariosId", idUsuario.ToString())
                                                };

                                                //Definiendo rol del usuario
                                                int rolId = (int)dr["RolId"];
                                                string rolNombre = rolId == 1 ? "Administrador" : "Usuario";
                                                claims.Add(new Claim(ClaimTypes.Role, rolNombre));

                                                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                                                var propiedades = new AuthenticationProperties
                                                {
                                                    //Opcion de mantener cuenta activa 
                                                    AllowRefresh = true,
                                                    IsPersistent = model.MantenerActivo,
                                                    ExpiresUtc = DateTimeOffset.UtcNow.Add(model.MantenerActivo ? TimeSpan.FromDays(1) : TimeSpan.FromMinutes(5))

                                                };

                                                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity), propiedades);
                                                return RedirectToAction("Index", "Home");
                                            }
                                        }
                                    }
                                }
                                else
                                    ViewBag.Error = "Correo no registrado";

InnoMasketss/Views/Shared/Partials/_CerrarCuentaModal.cshtml
<div class="modal fade" id="cerrarCuentaModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <form method="post" asp-action="EliminarCuenta" asp-controller="Usuario">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Cerrar cuenta</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    ¿Estas seguro que deseas eliminar tu cuenta permanentemente?
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger" type="submit">Eliminar cuenta</button>
                    <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </form>
    </div>
</div>

InnoMasketss/Views/Shared/Partials/_GrandChildComment.cshtml
@model IEnumerable<Comentario>

    @if (Model!=null && Model.Count()>0)
{
    <ul class="list.unstyledm mt-4 mb-0">
        @foreach (var grandchildcomment in Model)
        {
            <li class="mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@grandchildcomment.NombreUsuario
                            <small class="text-muted text-sm-end small">@grandchildcomment.FechaCreacion</small>
                        </h5>
                        <p class="card-text">@grandchildcomment.Contenido</p>
                    </div>
                </div>
            </li>
        }
    </ul>
}

InnoMasketss/Views/Shared/Partials/_Header.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">InnoMarkets</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("Index", "Home")">Inicio</a>,
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home", new{categoria="Noticia"})">Noticia</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home", new{ categoria="Opinion"})">Opinion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home", new{ categoria="Finanzas"})">Finanzas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home", new{ categoria="Consejos"})">Consejos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home", new{ categoria="Planificacion"})">Planificacion</a>
                    </li>
                </ul>

                <form class="d-flex" method="get" asp-controller="Home" asp-action="Index">
                    <input class="form-control me-2" type="search" placeholder="Buscar..." name="buscar">
                    <button class="btn btn-outline-secondary" type="submit">Buscar</button>
                </form>

                <ul class="navbar-nav ms-auto">
                    @if (!(User?.Identity?.IsAuthenticated ?? false))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Registrar" asp-controller="Cuenta">Registrarse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Login" asp-controller="Cuenta">Inicio sesion</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" id="userDropdown" data-bs-toggle="dropdown">
                                @User.FindFirstValue(ClaimTypes.NameIdentifier)
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li>
                                    <a class="dropdown-item" asp-action="Perfil" asp-controller="Usuario">Mi Perfil</a>
                                </li>
                                @if (User.IsInRole("Administrador"))
                                {
                                    <li>
                                        <a class="dropdown-item" asp-action="Create" asp-controller="Post">Crear post</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-action="Index" asp-controller="AdminUsuario">Administrar Usuarios</a>
                                    </li>
                                }
                                <li>
                                    <a class="dropdown-item" asp-action="CerrarSesion" asp-controller="Cuenta">Cerrar sesion</a>
                                </li>
                            </ul>
                        </li>
                    }

                </ul>

            </div>
        </div>

    </nav>
</header>